apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: ibm-entitlement-key
  namespace: openshift-marketplace
spec:
  encryptedData:
    .dockerconfigjson: AgBLoffhXdSWzKs7PmbAME0p0vZZ31R4KWVpg8bsuAuUWLAWoL2x3iaCLEo7LP/RxI3EzLFUgcb0pU2i3Zdnmy1aLpDCyUHqsNQvdr+sSYpYHiw/LdgTPjOIuT04eLXtea3ogFGIceLGh4entq/d2wkLfDyZOtyi2bG+uQ3+v6dRxdLnBM35iR7DBFhsRD7/u9WdBa3WI2AHdvu8Ph43Ot1+OEDkLT6ewSo09TA+KTuM802JHi6m60urcbR9h7yfZxCMAGJMZrR776JE/hRI2K1L/0KzfL7Q9jvPcl6l5Mbl1Pqowj1WsC50zElQa4aqLbxzJ1CjIcGvUYiq/TsTreMmB2acNiblRTylHWaYNUL7s0YfGJzuyO3knvfeE4EdBlhvEC78+a6Gok3ZFGVpVmIvQdm/SPev1EMKb9yJpDWCiTS6xA0T91gorSB+VIaWdx0sBFdNKp3L1Ki98FUKqGf4LVsvDRgj+4Wm6vLLtD/q52kMhazQTyddIOOrriALnDZvFyTRWr25JbOHMtky1mqFYi1UeXP4CbGe/t/seUunBGbTVGnbSYEqnCGmEatygdn7eIll0SVKkRqmAV3KLhtw5CGjKerMiIaglzhBDXuLIg9xbgTOxEm1Z/G3SIp5XGKiIe8JDtsY8swqBAi13XtwBv3kP3WmC/tDmyvdbXiIlC4rmbRAPQYQVyYVlXV2DupKEcLo4O225/b+oDd5rU2lT3vId0nl1o39FOhnm1fRTsjeeOkPQJzDDDLP5vy9QDclo77ZbDBaMtiRKdf7lKkIWdejDPMBdy250yaVlgvvjNnE9qHMAJDPc0MAUdOmdBoNXNcNzFOpUIdg3wa1EctZLcPMDhNJ16LrTslBoQvz2l1dnq81HgsJVF7bF+ceFXFEjZDMGQ+qZjOO1xY+ncXLP7KHz2kT9nX9qM67SRa9HzZ7okVrwCc6x+JMoNEzlZyW9iH2lPSU85zEIXKpW7pmdud5DT5c+bRGGNUsyUpBKuOssPRAeMCp5ZHQVdDjvoK9RsFGORSdhkPpZCxSbjnwyRZziEDHl53Lb1KdamirBy+Oefv2vixwQWec1ryfQ6owljTUwVPMlagBRV5FBevQH4coNeYRJZtgEZmN0YTYsWfebpmGIQHb11LxuE9oZFz/FOcD/Z13nqOF6PPECtEPX6DJjE6MAtIkihOaWSWTIXCwwdhA0E4p4t5qLlrYkoNUollVhEMVm4UinNoAompMRCAeKJq14ssvmCZh0mBQej8juY336TGydYJ/+XFuS8v3P29qQm9h+P/jOAa9uTlX2KoaszrKXLff0raQrcuO7I+EUyEYwui6CPBPW8xRqZy6
  template:
    data: null
    metadata:
      creationTimestamp: null
      name: ibm-entitlement-key
      namespace: openshift-marketplace
    type: kubernetes.io/dockerconfigjson

